# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  ServiceConnectionName: "DevTestConnection"
  ManagementGroupPrefix: "afli"
  TopLevelManagementGroupDisplayName: "Azure Landing Zones"
  Location: "SouthIndia"
  RunNumber: $(Build.BuildNumber)

- task: AzureCLI@2
    displayName: Az CLI Deploy Custom Policy Definitions
    name: create_policy_defs
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment mg create \
        --template-file infra-as-code/bicep/modules/policy/definitions/customPolicyDefinitions.bicep  \
        --parameters @infra-as-code/bicep/modules/policy/definitions/parameters/customPolicyDefinitions.parameters.all.json \
        --location $(Location) \
        --management-group-id $(ManagementGroupPrefix) \
        --name create_policy_defs-$(RunNumber)